/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example.avro;  

import java.util.Map;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserMap extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserMap\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"map\",\"values\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Long> name;

  /**
   * Default constructor.
   */
  public UserMap() {}

  /**
   * All-args constructor.
   */
  public UserMap(java.util.Map<java.lang.CharSequence,java.lang.Long> name) {
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.name = value;
  }

  /** Creates a new UserMap RecordBuilder */
  public static example.avro.UserMap.Builder newBuilder() {
    return new example.avro.UserMap.Builder();
  }
  
  /** Creates a new UserMap RecordBuilder by copying an existing Builder */
  public static example.avro.UserMap.Builder newBuilder(example.avro.UserMap.Builder other) {
    return new example.avro.UserMap.Builder(other);
  }
  
  /** Creates a new UserMap RecordBuilder by copying an existing UserMap instance */
  public static example.avro.UserMap.Builder newBuilder(example.avro.UserMap other) {
    return new example.avro.UserMap.Builder(other);
  }
  
  /**
   * RecordBuilder for UserMap instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserMap>
    implements org.apache.avro.data.RecordBuilder<UserMap> {

    private java.util.Map<java.lang.CharSequence,java.lang.Long> name;

    /** Creates a new Builder */
    private Builder() {
      super(example.avro.UserMap.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(example.avro.UserMap.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing UserMap instance */
    private Builder(example.avro.UserMap other) {
            super(example.avro.UserMap.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public example.avro.UserMap.Builder setName(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public example.avro.UserMap.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public UserMap build() {
      try {
        UserMap record = new UserMap();
        record.name = fieldSetFlags()[0] ? this.name : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

}
